export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_BOOKING = "CREATE_BOOKING";
export const LOAD_BOOKING_SUCCESS = "LOAD_BOOKING_SUCCESS";
export const LOAD_CHICKEN_COUNT = "LOAD_CHICKEN_COUNT";

